server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: testuser
    url: jdbc:sqlserver://localhost:1433;databaseName=todolist;encrypt=true;trustServerCertificate=true
    username: testuser
  mybatis:
    mapper-locations: classpath:mappers/*.xml
    configuration:
      map-underscore-to-camel-case: true